question_data = [
    {"category": "Geography", "type": "boolean",
     "difficulty": "easy",
     "question": "A group of islands is called an archipelago",
     "correct_answer": "True",
     "incorrect_answers": ["False"]},
    {"category": "Entertainment: Film", "type": "boolean",
     "difficulty": "easy",
     "question": "Leonardo DiCaprio won an Oscar for Best Actor in The Aviator",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"category": "Science: Computers", "type": "boolean",
     "difficulty": "easy",
     "question": "Pointers were not used in the original C programming language; they were added later on in C++.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"category": "Entertainment: Books", "type": "boolean",
     "difficulty": "easy",
     "question": "The Berenstein Bears is the correct spelling of the educational childrens book series name.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"category": "Geography", "type": "boolean", "difficulty": "easy",
     "question": "Alaska is the largest state in the United States.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "Entertainment: Japanese Anime & Manga",
     "type": "boolean", "difficulty": "easy",
     "question": "Studio Ghibli is a Japanese animation studio responsible for the films Wolf Children and The Boy and the Beast.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"category": "Entertainment: Video Games", "type": "boolean",
     "difficulty": "easy",
     "question": "Big the Cat is a playable character in Sonic Generations.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"category": "General Knowledge", "type": "boolean",
     "difficulty": "easy",
     "question": "Bulls are attracted to the color red.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"category": "Animals", "type": "boolean", "difficulty": "easy",
     "question": "The Killer Whale is considered a type of dolphin.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "Entertainment: Television", "type": "boolean",
     "difficulty": "easy",
     "question": "In Star Trek, Klaang is a typical Klingon male.",
     "correct_answer": "True", "incorrect_answers": ["False"]}
]